title: Nixie Creative
baseurl: /
permalink: '/:title/'
description: Web Design and Services
color_scheme: light
accent_color: violet
header:
  type: header
  title: Nixie Creative
  has_nav: true
  nav_links:
    - type: action
      label: Home
      url: /
      style: link
    - type: action
      label: About
      url: /about/
      style: link
    - type: action
      label: Portfolio
      url: /portfolio/
      style: link
    - type: action
      label: Blog
      url: /blog/
      style: link
    - type: action
      label: Contact
      url: /contact/
      style: link
  logo_img: /images/Nixie Creative Logo Image.png
  logo_img_alt: >-
    Purple hexagon logo with angled pink, blue, white and purple triangles
    inside
footer:
  type: footer
  content: Nixie Creative 2020
  has_social: true
  social_links:
    - type: action
      label: Twitter
      url: 'https://twitter.com/'
      style: icon
      icon_class: fa-twitter
      new_window: true
    - type: action
      label: Instagram
      url: 'https://www.instagram.com/'
      style: icon
      icon_class: fa-instagram
      new_window: true
    - type: action
      label: Dribbble
      url: 'https://dribbble.com/'
      style: icon
      icon_class: fa-dribbble
      new_window: true
    - type: action
      label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: icon
      icon_class: fa-linkedin
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
collections:
  posts:
    permalink: '/posts/:title/'
favicon: /images/superb-rosemary.png
